create table personas (
                          id bigint generated by default as identity,
                          apellido varchar(255) not null,
                          clave varchar(255) not null,
                          correo varchar(255) not null,
                          nombre varchar(255) not null,
                          primary key (id)
);

create table usuarios (
                          id bigint not null,
                          primary key (id)
);

create table administradores (
                                 id bigint not null,
                                 primary key (id)
);

create table categorias (
                            id bigint generated by default as identity,
                            descripcion varchar(255) not null,
                            nombre varchar(255) not null,
                            primary key (id)
);

create table articulos (
                           id bigint generated by default as identity,
                           id_categoria bigint unique,
                           id_usuario bigint,
                           descripcion varchar(255),
                           estado varchar(255) not null check (estado in ('DISPONIBLE','EN_NEGOCIACION','INTERCAMBIADO','DESACTIVADO')),
                           nombre varchar(255) not null,
                           ruta_imagen varchar(255),
                           primary key (id)
);

create table intercambios (
                              id bigint generated by default as identity,
                              fecha timestamp(6),
                              id_articulo_uno bigint not null unique,
                              id_articulo_dos bigint not null unique,
                              id_usuario_uno bigint not null,
                              id_usuario_dos bigint not null,
                              estado varchar(255) not null check (estado in ('SOLICITADO','ACEPTADO','REALIZADO','EN_NEGOCIACION','RECHAZADO','CANCELADO')),
                              primary key (id)
);

create table reportes (
                          id bigint generated by default as identity,
                          fecha_reporte timestamp(6) not null,
                          id_articulo bigint,
                          id_usuario bigint unique,
                          descripcion varchar(255) not null,
                          estado varchar(255) not null check (estado in ('ACTIVO','EN_REVISION','RESUELTO','DESCARTADO')),
                          primary key (id)
);

create table resenhas (
                          id bigint generated by default as identity,
                          puntuacion integer check (puntuacion >= 1 and puntuacion <= 5),
                          id_intercambio bigint not null,
                          id_usuario_calificado bigint unique,
                          id_autor bigint unique,
                          descripcion varchar(255) not null,
                          primary key (id)
);

create table administradores_reportes_activos (
                                                  id_administrador bigint not null,
                                                  id_reporte bigint not null unique
);

-- Foreign Keys

alter table administradores
    add constraint fk_administrador_persona
        foreign key (id) references personas;

alter table usuarios
    add constraint fk_usuario_persona
        foreign key (id) references personas;

alter table articulos
    add constraint fk_articulo_categoria
        foreign key (id_categoria) references categorias;

alter table articulos
    add constraint fk_articulo_usuario
        foreign key (id_usuario) references usuarios;

alter table intercambios
    add constraint fk_intercambio_articulo_uno
        foreign key (id_articulo_uno) references articulos;

alter table intercambios
    add constraint fk_intercambio_articulo_dos
        foreign key (id_articulo_dos) references articulos;

alter table intercambios
    add constraint fk_intercambio_usuario_uno
        foreign key (id_usuario_uno) references usuarios;

alter table intercambios
    add constraint fk_intercambio_usuario_dos
        foreign key (id_usuario_dos) references usuarios;

alter table reportes
    add constraint fk_reporte_articulo
        foreign key (id_articulo) references articulos;

alter table reportes
    add constraint fk_reporte_usuario
        foreign key (id_usuario) references usuarios;

alter table resenhas
    add constraint fk_resenha_intercambio
        foreign key (id_intercambio) references intercambios;

alter table resenhas
    add constraint fk_resenha_usuario_calificado
        foreign key (id_usuario_calificado) references usuarios;

alter table resenhas
    add constraint fk_resenha_autor
        foreign key (id_autor) references usuarios;

alter table administradores_reportes_activos
    add constraint fk_admin_reporte_admin
        foreign key (id_administrador) references administradores;

alter table administradores_reportes_activos
    add constraint fk_admin_reporte_reporte
        foreign key (id_reporte) references reportes;
