create table personas (
                          id bigint generated by default as identity primary key,
                          apellido varchar(100) not null,
                          nombre varchar(100) not null,
                          correo varchar(150),
                          clave varchar(255) not null
);

create table administradores (
                                 id bigint not null,
                                 primary key (id),
                                 constraint FK_administrador_persona foreign key (id) references personas(id)
);

create table usuarios (
                          id bigint not null,
                          primary key (id),
                          constraint FK_usuario_persona foreign key (id) references personas(id)
);

create table categorias (
                            id bigint generated by default as identity primary key,
                            nombre varchar(255) not null,
                            descripcion varchar(255) not null
);

create table articulos (
                           id bigint generated by default as identity primary key,
                           id_categoria bigint unique,
                           id_usuario bigint,
                           nombre varchar(255) not null,
                           descripcion varchar(255),
                           estado varchar(255) not null,
                           ruta_imagen varchar(255),
                           constraint FK_articulo_categoria foreign key (id_categoria) references categorias(id),
                           constraint FK_articulo_usuario foreign key (id_usuario) references usuarios(id),
                           constraint CHK_articulo_estado check (estado in ('DISPONIBLE', 'EN_NEGOCIACION', 'INTERCAMBIADO', 'DESACTIVADO'))
);

create table reportes (
                          id bigint generated by default as identity primary key,
                          fecha_reporte timestamp(6) not null,
                          id_articulo bigint,
                          id_usuario bigint unique,
                          descripcion varchar(255) not null,
                          estado varchar(255) not null,
                          constraint FK_reporte_articulo foreign key (id_articulo) references articulos(id),
                          constraint FK_reporte_usuario foreign key (id_usuario) references usuarios(id),
                          constraint CHK_reporte_estado check (estado in ('ACTIVO', 'EN_REVISION', 'RESUELTO', 'DESCARTADO'))
);

create table administradores_reportes_activos (
                                                  id_administrador bigint not null,
                                                  id_reporte bigint not null unique,
                                                  constraint FK_admin_reportes_admin foreign key (id_administrador) references administradores(id),
                                                  constraint FK_admin_reportes_reporte foreign key (id_reporte) references reportes(id)
);

create table intercambios (
                              id bigint generated by default as identity primary key,
                              fecha timestamp(6),
                              id_articulo_uno bigint not null unique,
                              id_articulo_dos bigint not null unique,
                              id_usuario_uno bigint not null,
                              id_usuario_dos bigint not null,
                              estado varchar(255) not null,
                              constraint FK_intercambio_articulo_uno foreign key (id_articulo_uno) references articulos(id),
                              constraint FK_intercambio_articulo_dos foreign key (id_articulo_dos) references articulos(id),
                              constraint FK_intercambio_usuario_uno foreign key (id_usuario_uno) references usuarios(id),
                              constraint FK_intercambio_usuario_dos foreign key (id_usuario_dos) references usuarios(id),
                              constraint CHK_intercambio_estado check (estado in ('SOLICITADO', 'ACEPTADO', 'REALIZADO', 'EN_NEGOCIACION', 'CANCELADO'))
);

create table resenhas (
                          id bigint generated by default as identity primary key,
                          id_autor bigint unique,
                          id_intercambio bigint not null,
                          puntuacion integer,
                          descripcion varchar(255) not null,
                          constraint FK_resenha_autor foreign key (id_autor) references usuarios(id),
                          constraint FK_resenha_intercambio foreign key (id_intercambio) references intercambios(id),
                          constraint CHK_resenha_puntuacion check (puntuacion >= 1 and puntuacion <= 5)
);
