create table personas (
                          id bigint generated by default as identity,
                          apellido varchar(100) not null,
                          nombre varchar(100) not null,
                          correo varchar(150),
                          clave varchar(255) not null,
                          primary key (id)
);

create table administradores (
                                 id bigint not null,
                                 primary key (id)
);

create table categorias (
                            id bigint generated by default as identity,
                            descripcion varchar(255) not null,
                            nombre varchar(255) not null,
                            primary key (id)
);

create table usuarios (
                          id bigint not null,
                          primary key (id)
);

create table articulos (
                           id bigint generated by default as identity,
                           id_categoria bigint unique,
                           usuario_id bigint,
                           descripcion varchar(255) not null,
                           estado varchar(255) not null check (estado in ('DISPONIBLE','EN_NEGOCIACION','INTERCAMBIADO','DESACTIVADO')),
                           nombre varchar(255) not null,
                           ruta_imagen varchar(255),
                           primary key (id)
);

create table intercambios (
                              id bigint generated by default as identity,
                              id_articulo_dos bigint not null unique,
                              id_articulo_uno bigint not null unique,
                              id_usuario_dos bigint not null,
                              id_usuario_uno bigint not null,
                              fecha timestamp(6),
                              estado varchar(255) not null check (estado in ('SOLICITADO','ACEPTADO','REALIZADO','EN_NEGOCIACION','CANCELADO')),
                              primary key (id)
);

create table reportes (
                          id bigint generated by default as identity,
                          articulo_id bigint,
                          usuario_id bigint unique,
                          fecha_reporte timestamp(6) not null,
                          descripcion varchar(255) not null,
                          estado varchar(255) not null check (estado in ('ACTIVO','EN_REVISION','RESUELTO','DESCARTADO')),
                          primary key (id)
);

create table resenhas (
                          id bigint generated by default as identity,
                          autor_id bigint unique,
                          intercambio_id bigint not null,
                          puntuacion integer check (puntuacion >= 1 and puntuacion <= 5),
                          descripcion varchar(255) not null,
                          primary key (id)
);

create table administradores_reportes_activos (
                                                  administrador_id bigint not null,
                                                  reportes_activos_id bigint not null unique
);

-- Foreign Keys

alter table administradores
    add constraint fk_admin_persona foreign key (id) references personas;

alter table administradores_reportes_activos
    add constraint fk_admin_reportes_admin foreign key (administrador_id) references administradores;

alter table administradores_reportes_activos
    add constraint fk_admin_reportes_reporte foreign key (reportes_activos_id) references reportes;

alter table articulos
    add constraint fk_articulo_categoria foreign key (id_categoria) references categorias;

alter table articulos
    add constraint fk_articulo_usuario foreign key (usuario_id) references usuarios;

alter table intercambios
    add constraint fk_intercambio_articulo_uno foreign key (id_articulo_uno) references articulos;

alter table intercambios
    add constraint fk_intercambio_articulo_dos foreign key (id_articulo_dos) references articulos;

alter table intercambios
    add constraint fk_intercambio_usuario_uno foreign key (id_usuario_uno) references usuarios;

alter table intercambios
    add constraint fk_intercambio_usuario_dos foreign key (id_usuario_dos) references usuarios;

alter table reportes
    add constraint fk_reporte_articulo foreign key (articulo_id) references articulos;

alter table reportes
    add constraint fk_reporte_usuario foreign key (usuario_id) references usuarios;

alter table resenhas
    add constraint fk_resenha_autor foreign key (autor_id) references usuarios;

alter table resenhas
    add constraint fk_resenha_intercambio foreign key (intercambio_id) references intercambios;

alter table usuarios
    add constraint fk_usuario_persona foreign key (id) references personas;
